CREATE TYPE tipo_usuario AS ENUM (
  'hospede',
  'locador'
);

CREATE TYPE tipo_propriedade AS ENUM (
  'casa_inteira',
  'quarto_privativo',
  'quarto_compartilhado'
);

CREATE TYPE status_reserva AS ENUM (
  'pendente',
  'confirmada',
  'cancelada'
);

CREATE TABLE localizacao (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cidade varchar NOT NULL,
  estado varchar NOT NULL,
  pais varchar NOT NULL,
  cep varchar NOT NULL,
  bairro varchar
);

CREATE TABLE usuario (
  cpf varchar PRIMARY KEY,
  nome varchar NOT NULL,
  sobrenome varchar NOT NULL,
  data_nascimento date NOT NULL,
  endereco varchar NOT NULL,
  sexo varchar NOT NULL,
  telefone varchar UNIQUE NOT NULL,
  email varchar UNIQUE NOT NULL,
  senha varchar NOT NULL,
  tipo tipo_usuario NOT NULL,
  loc_id int NOT NULL,
  FOREIGN KEY (loc_id) REFERENCES localizacao (id)
);

CREATE TABLE ponto_interesse (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar,
  loc_id int NOT NULL,
  FOREIGN KEY (loc_id) REFERENCES localizacao (id)
);

CREATE TABLE locador (
  cpf varchar PRIMARY KEY,
  FOREIGN KEY (cpf) REFERENCES usuario (cpf)
);

CREATE TABLE hospede (
  cpf varchar PRIMARY KEY,
  FOREIGN KEY (cpf) REFERENCES usuario (cpf)
);

CREATE TABLE conta_bancaria (
  numero_conta varchar PRIMARY KEY,
  agencia varchar NOT NULL,
  tipo_conta varchar NOT NULL,
  locador_cpf varchar NOT NULL,
  FOREIGN KEY (locador_cpf) REFERENCES locador (cpf)
);

CREATE TABLE propriedade (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar NOT NULL,
  endereco varchar NOT NULL,
  tipo tipo_propriedade NOT NULL,
  num_quartos int NOT NULL,
  num_banheiros int NOT NULL,
  preco_noite decimal NOT NULL,
  max_hospedes int NOT NULL,
  min_noites int NOT NULL,
  max_noites int NOT NULL,
  taxa_limpeza decimal,
  checkin_hora time,
  checkout_hora time,
  locador_cpf varchar NOT NULL,
  loc_id int NOT NULL,
  FOREIGN KEY (locador_cpf) REFERENCES locador (cpf),
  FOREIGN KEY (loc_id) REFERENCES localizacao (id)
);

CREATE TABLE quarto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prop_id int NOT NULL,
  num_camas int NOT NULL,
  tipo_cama varchar NOT NULL,
  banheiro_privativo boolean NOT NULL,
  FOREIGN KEY (prop_id) REFERENCES propriedade (id)
);

CREATE TABLE comodidade (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar
);

CREATE TABLE propriedade_comodidade (
  prop_id int NOT NULL,
  comod_id int NOT NULL,
  PRIMARY KEY (prop_id, comod_id),
  FOREIGN KEY (prop_id) REFERENCES propriedade (id),
  FOREIGN KEY (comod_id) REFERENCES comodidade (id)
);

CREATE TABLE regra (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao varchar
);

CREATE TABLE propriedade_regra (
  prop_id int NOT NULL,
  regra_id int NOT NULL,
  PRIMARY KEY (prop_id, regra_id),
  FOREIGN KEY (prop_id) REFERENCES propriedade (id),
  FOREIGN KEY (regra_id) REFERENCES regra (id)
);

CREATE TABLE reserva (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospede_cpf varchar NOT NULL,
  prop_id int NOT NULL,
  data_reserva date NOT NULL,
  data_checkin date NOT NULL,
  data_checkout date NOT NULL,
  num_hospedes int NOT NULL,
  imposto_pago decimal,
  preco_total decimal,
  preco_total_impostos decimal,
  taxa_limpeza decimal,
  status status_reserva NOT NULL,
  status_data timestamp DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (hospede_cpf) REFERENCES hospede (cpf),
  FOREIGN KEY (prop_id) REFERENCES propriedade (id),
  CHECK (status_data IS NULL OR status_data < data_checkin)
);

CREATE TABLE avaliacao (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id int,
  hospede_cpf varchar NOT NULL,
  prop_id int NOT NULL,
  texto varchar NOT NULL,
  nota_limpeza int,
  nota_estrutura int,
  nota_comunicacao int,
  nota_localizacao int,
  nota_valor int,
  FOREIGN KEY (reserva_id) REFERENCES reserva (id),
  FOREIGN KEY (hospede_cpf) REFERENCES hospede (cpf),
  FOREIGN KEY (prop_id) REFERENCES propriedade (id)
);

CREATE TABLE mensagem_aval (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  remetente_cpf varchar NOT NULL,
  destinatario_cpf varchar NOT NULL,
  ts timestamp DEFAULT CURRENT_TIMESTAMP,
  texto varchar NOT NULL,
  aval_id int NOT NULL,
  FOREIGN KEY (remetente_cpf) REFERENCES usuario (cpf),
  FOREIGN KEY (destinatario_cpf) REFERENCES usuario (cpf),
  FOREIGN KEY (aval_id) REFERENCES avaliacao (id)
);

CREATE TABLE foto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url varchar NOT NULL,
  aval_id int NOT NULL,
  FOREIGN KEY (aval_id) REFERENCES avaliacao (id)
);

CREATE TABLE mensagem_chat (
  id int PRIMARY KEY,
  remetente_cpf varchar NOT NULL,
  destinatario_cpf varchar NOT NULL,
  ts timestamp DEFAULT CURRENT_TIMESTAMP,
  texto varchar NOT NULL,
  FOREIGN KEY (remetente_cpf) REFERENCES usuario (cpf),
  FOREIGN KEY (destinatario_cpf) REFERENCES usuario (cpf)
);