CREATE TABLE "usuario" (
  "cpf" varchar PRIMARY KEY,
  "nome" varchar,
  "sobrenome" varchar,
  "data_nascimento" date,
  "endereco" varchar,
  "sexo" varchar,
  "telefone" varchar,
  "email" varchar,
  "senha" varchar,
  "loc_id" int
);

CREATE TABLE "localizacao" (
  "loc_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cidade" varchar,
  "estado" varchar,
  "pais" varchar,
  "cep" varchar,
  "bairro" varchar
);

CREATE TABLE "ponto_interesse" (
  "poi_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "loc_id" int
);

CREATE TABLE "locador" (
  "cpf" varchar PRIMARY KEY
);

CREATE TABLE "hospede" (
  "cpf" varchar PRIMARY KEY
);

CREATE TABLE "conta_bancaria" (
  "numero_conta" varchar PRIMARY KEY,
  "agencia" varchar,
  "tipo_conta" varchar,
  "locador_cpf" varchar
);

CREATE TABLE "propriedade" (
  "prop_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar,
  "endereco" varchar,
  "tipo" varchar,
  "num_quartos" int,
  "num_banheiros" int,
  "preco_noite" decimal,
  "max_hospedes" int,
  "min_noites" int,
  "max_noites" int,
  "taxa_limpeza" decimal,
  "checkin_hora" time,
  "checkout_hora" time,
  "locador_cpf" varchar,
  "loc_id" int
);

CREATE TABLE "disponibilidade" (
  "disp_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prop_id" int,
  "data_inicio" date,
  "data_fim" date
);

CREATE TABLE "quarto" (
  "quarto_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "prop_id" int,
  "num_camas" int,
  "tipo_cama" varchar,
  "banheiro_privativo" boolean
);

CREATE TABLE "comodidade" (
  "comod_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar
);

CREATE TABLE "propriedade_comodidade" (
  "prop_id" int,
  "comod_id" int,
  PRIMARY KEY ("prop_id", "comod_id")
);

CREATE TABLE "regra" (
  "regra_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar
);

CREATE TABLE "propriedade_regra" (
  "prop_id" int,
  "regra_id" int,
  PRIMARY KEY ("prop_id", "regra_id")
);

CREATE TABLE "reserva" (
  "res_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hospede_cpf" varchar,
  "prop_id" int,
  "data_reserva" date,
  "data_checkin" date,
  "data_checkout" date,
  "num_hospedes" int,
  "imposto_pago" decimal,
  "preco_total" decimal,
  "preco_total_impostos" decimal,
  "taxa_limpeza" decimal,
  "status" varchar,
  "data_status" date
);

CREATE TABLE "avaliacao" (
  "aval_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int,
  "hospede_cpf" varchar,
  "prop_id" int,
  "texto" varchar,
  "nota_limpeza" int,
  "nota_estrutura" int,
  "nota_comunicacao" int,
  "nota_localizacao" int,
  "nota_valor" int
);

CREATE TABLE "mensagem" (
  "msg_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "remetente_cpf" varchar,
  "destinatario_cpf" varchar,
  "ts" datetime,
  "texto" varchar,
  "aval_id" int
);

CREATE TABLE "foto" (
  "foto_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar,
  "avaliacao_id" int
);

ALTER TABLE "usuario" ADD FOREIGN KEY ("loc_id") REFERENCES "localizacao" ("loc_id");

ALTER TABLE "ponto_interesse" ADD FOREIGN KEY ("loc_id") REFERENCES "localizacao" ("loc_id");

ALTER TABLE "locador" ADD FOREIGN KEY ("cpf") REFERENCES "usuario" ("cpf");

ALTER TABLE "hospede" ADD FOREIGN KEY ("cpf") REFERENCES "usuario" ("cpf");

ALTER TABLE "propriedade" ADD FOREIGN KEY ("locador_cpf") REFERENCES "locador" ("cpf");

ALTER TABLE "conta_bancaria" ADD FOREIGN KEY ("locador_cpf") REFERENCES "locador" ("cpf");

ALTER TABLE "propriedade" ADD FOREIGN KEY ("prop_id") REFERENCES "disponibilidade" ("prop_id");

ALTER TABLE "propriedade" ADD FOREIGN KEY ("prop_id") REFERENCES "quarto" ("prop_id");

ALTER TABLE "propriedade_comodidade" ADD FOREIGN KEY ("prop_id") REFERENCES "propriedade" ("prop_id");

ALTER TABLE "propriedade_comodidade" ADD FOREIGN KEY ("comod_id") REFERENCES "comodidade" ("comod_id");

ALTER TABLE "propriedade_regra" ADD FOREIGN KEY ("prop_id") REFERENCES "propriedade" ("prop_id");

ALTER TABLE "propriedade_regra" ADD FOREIGN KEY ("regra_id") REFERENCES "regra" ("regra_id");

ALTER TABLE "reserva" ADD FOREIGN KEY ("hospede_cpf") REFERENCES "hospede" ("cpf");

ALTER TABLE "reserva" ADD FOREIGN KEY ("prop_id") REFERENCES "propriedade" ("prop_id");

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("res_id");

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("hospede_cpf") REFERENCES "hospede" ("cpf");

ALTER TABLE "avaliacao" ADD FOREIGN KEY ("prop_id") REFERENCES "propriedade" ("prop_id");

ALTER TABLE "mensagem" ADD FOREIGN KEY ("remetente_cpf") REFERENCES "usuario" ("cpf");

ALTER TABLE "mensagem" ADD FOREIGN KEY ("destinatario_cpf") REFERENCES "usuario" ("cpf");

ALTER TABLE "mensagem" ADD FOREIGN KEY ("aval_id") REFERENCES "avaliacao" ("aval_id");

ALTER TABLE "foto" ADD FOREIGN KEY ("avaliacao_id") REFERENCES "avaliacao" ("aval_id");